apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openperouter-system

resources:
- rbac.yaml
- deployment.yaml
images:
- name: router
  newName: quay.io/openperouter/router
  newTag: main
