frr version 10.2.1_git
frr defaults traditional
hostname leafgcp
log file /etc/frr/frr.log
!
debug zebra events
debug zebra vxlan
debug bgp keepalives
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
debug bgp zebra
!
router bgp 64515
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 neighbor gcp-workers peer-group
 neighbor gcp-workers remote-as external
 neighbor gcp-workers ebgp-multihop 10
 neighbor 10.250.1.2 remote-as 64612
 neighbor 169.254.0.1 remote-as 65001
 neighbor 169.254.0.1 description GCP Cloud Router
 neighbor 169.254.0.1 ebgp-multihop 4
 neighbor 169.254.0.1 update-source 169.254.0.2
 bgp listen range 192.168.11.0/24 peer-group gcp-workers
 !
 address-family ipv4 unicast
  network 10.250.1.0/24
  network 10.250.11.0/24
  network 100.64.0.0/24
  network 100.65.0.0/24
  neighbor gcp-workers activate
  neighbor 10.250.1.2 activate
  neighbor 169.254.0.1 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor gcp-workers activate
  neighbor 10.250.1.2 activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
exit
!
