openperouter:
  runOnMaster: false
  logLevel: debug
  multusNetworkAnnotation:
      '[{ "name": "underlay", "namespace": "openperouter-system" }]'
  cri: crio
  image:
    tag: gcp
    repository: quay.io/ellorent/router
    pullPolicy: Always
